//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HilalKepenk
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLFATURADETAY
    {
        public int FATURADETAYID { get; set; }
        public string URUNKODU { get; set; }
        public string ACIKLAMA { get; set; }
        public string RENK { get; set; }
        public string MİKTAR { get; set; }
        public string BIRIM { get; set; }
        public Nullable<decimal> BIRIMFIYAT { get; set; }
        public Nullable<decimal> TUTAR { get; set; }
        public Nullable<int> FATURAID { get; set; }
    
        public virtual TBLFATURABILGI TBLFATURABILGI { get; set; }
    }
}
